Repository lowell-dashboard/lowell-dashboard, pull requests merged in 2019-06, with the labels that each got.

#17 adding pagination for news posts
  lowell-dashboard/app/static/css/all_files.css
  lowell-dashboard/app/static/js/all_files.js
  lowell-dashboard/app/templates/disclaimer.html
  lowell-dashboard/app/templates/license.html
  lowell-dashboard/app/templates/navbar.html
  lowell-dashboard/app/templates/news.html
  lowell-dashboard/app/templates/post.html
  lowell-dashboard/app/templates/user_posts.html
  lowell-dashboard/app/views.py
Labels: enhancement

#18 adding password reset
  lowell-dashboard/app/__init__.py
  lowell-dashboard/app/forms.py
  lowell-dashboard/app/models.py
  lowell-dashboard/app/templates/login.html
  lowell-dashboard/app/templates/reset_request.html
  lowell-dashboard/app/templates/reset_token.html
  lowell-dashboard/app/views.py
Labels: enhancement

#19 Create email activation account
  lowell-dashboard/app/__init__.py
  lowell-dashboard/app/config.py
  lowell-dashboard/app/email.py
  lowell-dashboard/app/forms.py
  lowell-dashboard/app/initializedb.py
  lowell-dashboard/app/models.py
  lowell-dashboard/app/templates/activation.html
  lowell-dashboard/app/templates/base.html
  lowell-dashboard/app/templates/footer.html
  lowell-dashboard/app/templates/reset_email.html
  lowell-dashboard/app/token.py
  lowell-dashboard/app/views.py
  requirements.txt
Labels: enhancement, improvement

#21 Fix html file spacing and add jinja blocks
  lowell-dashboard/app/config.py
  lowell-dashboard/app/forms.py
  lowell-dashboard/app/templates/new_post.html
  lowell-dashboard/app/templates/news.html
  lowell-dashboard/app/templates/post.html
  lowell-dashboard/app/templates/register.html
  lowell-dashboard/app/templates/reset_request.html
  lowell-dashboard/app/templates/reset_token.html
  lowell-dashboard/app/templates/user_posts.html
  lowell-dashboard/app/views.py
Labels: improvement

#24 add new colors and styling to login form
  lowell-dashboard/app/models.py
  lowell-dashboard/app/static/css/base.css
  lowell-dashboard/app/static/css/flash.css
  lowell-dashboard/app/static/css/footer.css
  lowell-dashboard/app/static/css/home.css
  lowell-dashboard/app/static/css/login.css
  lowell-dashboard/app/templates/flash.html
  lowell-dashboard/app/templates/footer.html
  lowell-dashboard/app/templates/login.html
Labels: enhancement, improvement

#25 Rafbranch
  lowell-dashboard/app/static/css/404.css
  lowell-dashboard/app/static/css/footer.css
  lowell-dashboard/app/static/css/form.css
  lowell-dashboard/app/static/css/grid.css
  lowell-dashboard/app/static/css/login.css
  lowell-dashboard/app/static/css/navbar.css
  lowell-dashboard/app/templates/404.html
  lowell-dashboard/app/templates/footer.html
  lowell-dashboard/app/templates/login.html
  lowell-dashboard/app/templates/navbar.html
  lowell-dashboard/app/templates/reset_request.html
  lowell-dashboard/app/views.py
Labels: enhancement, improvement
